learn_reward: False
num_iters: 4000
use_acquisition: True
rollout_sampling: False
n_rand_acqopt: 1
use_mpc: False
kgrl: True
num_fs: 15
num_s0: 5
num_sprime_samps: 5
learning_rate: 0.001
num_steps: 10000
hidden_layer_sizes: [128, 128]
